name: .NET CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests with Coverage
        run: dotnet test --configuration Release --collect:"XPlat Code Coverage"

      - name: Publish Application
        run: dotnet publish -c Release -o publish --no-build

      - name: Deploy to EC2 Windows
        shell: pwsh
        run: |
          winrm set winrm/config/client '@{TrustedHosts="*"}'
          winrm set winrm/config/client '@{AllowUnencrypted="true"}'
      
          $password = ConvertTo-SecureString "${{ secrets.EC2_PASSWORD }}" -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential ("${{ secrets.EC2_USER }}", $password)
      
          $sessionOptions = New-PSSessionOption -SkipCACheck -SkipCNCheck -SkipRevocationCheck
      
          $session = New-PSSession `
            -ComputerName "${{ secrets.EC2_HOST }}" `
            -Credential $cred `
            -Port 5985 `
            -Authentication Basic `
            -SessionOption $sessionOptions
      
          Invoke-Command -Session $session -ScriptBlock {
      
              # Stop existing app if running
              Get-Process EpayDbMigrator -ErrorAction SilentlyContinue | Stop-Process -Force
      
              if (!(Test-Path "C:\apps\epay")) {
                  New-Item -ItemType Directory -Path "C:\apps\epay"
              } else {
                  Remove-Item "C:\apps\epay\*" -Recurse -Force
              }
          }
      
          Copy-Item -Path publish\* -Destination C:\apps\epay -Recurse -Force -ToSession $session
      
          Invoke-Command -Session $session -ScriptBlock {
              cd C:\apps\epay
              Start-Process "EpayDbMigrator.exe"
          }
      
          Remove-PSSession $session
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-build
          path: publish

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: TestResults
