name: .NET CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests with Coverage
        run: dotnet test --configuration Release --collect:"XPlat Code Coverage"
      
      - name: Publish Application
        run: dotnet publish -c Release -o publish
     
      - name: Deploy to EC2 Windows
        uses: nttld/setup-winrm@v1
        with:
          hostname: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          password: ${{ secrets.EC2_PASSWORD }}
          port: 5985
          script: |
            if (!(Test-Path "C:\apps\epay")) {
              New-Item -ItemType Directory -Path "C:\apps\epay"
            }

      - name: Copy files to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          password: ${{ secrets.EC2_PASSWORD }}
          source: "publish/*"
          target: "C:/apps/epay"

      - name: Run application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          password: ${{ secrets.EC2_PASSWORD }}
          script: |
            cd C:\apps\epay
            EpayDbMigrator.exe
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-build
          path: publish
          
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: 'TestResults'
